import { Metadata } from 'next'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'

export const metadata: Metadata = {
  title: 'Terms of Service | Scenra',
  description: 'Terms of Service for Scenra - AI-powered video prompt generation platform',
}

export default function TermsOfServicePage() {
  const effectiveDate = 'January 3, 2025'
  const version = '1.0'

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="text-center space-y-4">
        <Badge variant="outline" className="text-amber-700 border-amber-300 bg-amber-50">
          Version {version}
        </Badge>
        <h1 className="text-4xl font-bold tracking-tight">Terms of Service</h1>
        <p className="text-muted-foreground">
          Effective Date: {effectiveDate}
        </p>
      </div>

      {/* Content */}
      <Card>
        <CardContent className="prose prose-gray dark:prose-invert max-w-none p-8">
          <section className="space-y-6">
            <div>
              <h2 className="text-2xl font-semibold mt-0">1. Acceptance of Terms</h2>
              <p>
                Welcome to Scenra ("Company," "we," "our," or "us"). By accessing or using our AI-powered video prompt generation platform at scenra.io (the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of these terms, you may not access the Service.
              </p>
              <p>
                By creating an account, you represent that you are at least 18 years of age and have the legal capacity to enter into these Terms. If you are using the Service on behalf of an organization, you represent that you have the authority to bind that organization to these Terms.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold">2. Description of Service</h2>
              <p>
                Scenra provides an AI-powered creative production platform that helps users:
              </p>
              <ul>
                <li>Generate optimized video prompts for AI video generation tools (such as Sora, Runway, and similar services)</li>
                <li>Collaborate with AI agents to refine creative concepts</li>
                <li>Organize video projects, series, and episodes</li>
                <li>Create shot lists and production materials</li>
                <li>Export and share generated prompts</li>
              </ul>
              <p>
                The Service utilizes artificial intelligence, including third-party AI services such as OpenAI's GPT models, to generate content suggestions and optimizations.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold">3. User Accounts</h2>
              <h3 className="text-xl font-medium">3.1 Account Creation</h3>
              <p>
                To use certain features of the Service, you must create an account. You agree to provide accurate, current, and complete information during registration and to update such information to keep it accurate, current, and complete.
              </p>
              <h3 className="text-xl font-medium">3.2 Account Security</h3>
              <p>
                You are responsible for safeguarding your account credentials and for all activities that occur under your account. You must immediately notify us of any unauthorized use of your account or any other security breach.
              </p>
              <h3 className="text-xl font-medium">3.3 Account Termination</h3>
              <p>
                We reserve the right to suspend or terminate your account at any time for violation of these Terms or for any other reason at our sole discretion, with or without notice.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold">4. AI-Generated Content</h2>
              <h3 className="text-xl font-medium">4.1 Nature of AI Output</h3>
              <p>
                The prompts, suggestions, and other content generated by our AI systems ("AI Output") are produced by artificial intelligence algorithms. AI Output may not always be accurate, complete, or suitable for your intended purpose.
              </p>
              <h3 className="text-xl font-medium">4.2 No Warranty on AI Output</h3>
              <p>
                <strong>WE MAKE NO WARRANTIES OR REPRESENTATIONS REGARDING THE ACCURACY, RELIABILITY, COMPLETENESS, OR SUITABILITY OF ANY AI OUTPUT.</strong> You acknowledge that AI Output may contain errors, biases, or inappropriate content, and you are solely responsible for reviewing and verifying any AI Output before use.
              </p>
              <h3 className="text-xl font-medium">4.3 Your Responsibility</h3>
              <p>
                You are solely responsible for:
              </p>
              <ul>
                <li>Reviewing all AI Output before use in any production or commercial context</li>
                <li>Ensuring AI Output complies with applicable laws and regulations</li>
                <li>Verifying that AI Output does not infringe on third-party intellectual property rights</li>
                <li>Any consequences arising from your use of AI Output</li>
              </ul>
              <h3 className="text-xl font-medium">4.4 Ownership of AI Output</h3>
              <p>
                Subject to these Terms and any applicable third-party licenses, you retain ownership of the prompts and creative materials you generate using the Service. However, you grant us a non-exclusive, worldwide, royalty-free license to use, reproduce, and display such content solely for the purpose of providing and improving the Service.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold">5. Acceptable Use Policy</h2>
              <p>
                You agree NOT to use the Service to:
              </p>
              <ul>
                <li>Generate content that is illegal, harmful, threatening, abusive, harassing, defamatory, or otherwise objectionable</li>
                <li>Create prompts intended to generate content depicting minors in inappropriate situations</li>
                <li>Produce content that infringes on intellectual property rights of third parties</li>
                <li>Generate deepfakes or deceptive media intended to mislead or harm</li>
                <li>Create content that promotes violence, discrimination, or hatred</li>
                <li>Violate any applicable laws or regulations</li>
                <li>Attempt to reverse engineer, decompile, or extract the underlying AI models</li>
                <li>Use automated systems to access the Service in a manner that exceeds reasonable use</li>
                <li>Share your account credentials with third parties</li>
                <li>Resell or redistribute the Service without our express written permission</li>
              </ul>
              <p>
                We reserve the right to remove any content that violates these guidelines and to terminate accounts that repeatedly violate our policies.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold">6. Intellectual Property</h2>
              <h3 className="text-xl font-medium">6.1 Our Intellectual Property</h3>
              <p>
                The Service, including its original content (excluding user-generated content), features, and functionality, is owned by Scenra and is protected by international copyright, trademark, patent, trade secret, and other intellectual property laws.
              </p>
              <h3 className="text-xl font-medium">6.2 Your Content</h3>
              <p>
                You retain all rights to the content you input into the Service ("User Content"). By submitting User Content, you grant us a limited license to process such content solely for providing the Service to you.
              </p>
              <h3 className="text-xl font-medium">6.3 Feedback</h3>
              <p>
                If you provide feedback, suggestions, or ideas about the Service, you grant us an unrestricted, perpetual, irrevocable, royalty-free license to use such feedback without any obligation to you.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold">7. Third-Party Services</h2>
              <p>
                The Service integrates with third-party services, including but not limited to:
              </p>
              <ul>
                <li><strong>OpenAI:</strong> For AI-powered content generation</li>
                <li><strong>Supabase:</strong> For authentication and data storage</li>
                <li><strong>Vercel:</strong> For hosting and infrastructure</li>
              </ul>
              <p>
                Your use of these third-party services is subject to their respective terms of service and privacy policies. We are not responsible for the practices or content of third-party services.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold">8. Subscription and Payment</h2>
              <h3 className="text-xl font-medium">8.1 Free and Paid Tiers</h3>
              <p>
                The Service may offer both free and paid subscription tiers. Features, usage limits, and pricing are subject to change with reasonable notice.
              </p>
              <h3 className="text-xl font-medium">8.2 Billing</h3>
              <p>
                For paid subscriptions, you agree to pay all fees associated with your chosen plan. Payments are processed through our third-party payment processors and are subject to their terms.
              </p>
              <h3 className="text-xl font-medium">8.3 Refunds</h3>
              <p>
                Subscription fees are generally non-refundable except as required by applicable law or as explicitly stated in our refund policy.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold">9. Disclaimers</h2>
              <p className="uppercase font-semibold">
                THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR COURSE OF PERFORMANCE.
              </p>
              <p>
                We do not warrant that:
              </p>
              <ul>
                <li>The Service will be uninterrupted, secure, or error-free</li>
                <li>The results obtained from the Service will be accurate or reliable</li>
                <li>Any AI-generated content will be suitable for any particular purpose</li>
                <li>Any defects in the Service will be corrected</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl font-semibold">10. Limitation of Liability</h2>
              <p className="uppercase font-semibold">
                TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL SCENRA, ITS DIRECTORS, EMPLOYEES, PARTNERS, AGENTS, SUPPLIERS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM:
              </p>
              <ul>
                <li>Your access to or use of (or inability to access or use) the Service</li>
                <li>Any conduct or content of any third party on the Service</li>
                <li>Any AI-generated content obtained from the Service</li>
                <li>Unauthorized access, use, or alteration of your transmissions or content</li>
              </ul>
              <p>
                Our total liability for any claims arising out of or relating to these Terms or the Service shall not exceed the amount you paid us in the twelve (12) months preceding the claim.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold">11. Indemnification</h2>
              <p>
                You agree to defend, indemnify, and hold harmless Scenra and its officers, directors, employees, and agents from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising out of or relating to your violation of these Terms or your use of the Service.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold">12. Changes to Terms</h2>
              <p>
                We reserve the right to modify these Terms at any time. We will provide notice of material changes by posting the new Terms on the Service and updating the "Effective Date" above. Your continued use of the Service after such modifications constitutes your acceptance of the updated Terms.
              </p>
              <p>
                For material changes that significantly affect your rights, we will provide at least 30 days' notice before the changes take effect.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold">13. Governing Law and Dispute Resolution</h2>
              <p>
                These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to its conflict of law provisions.
              </p>
              <p>
                Any disputes arising out of or relating to these Terms or the Service shall first be attempted to be resolved through good-faith negotiation. If negotiation fails, disputes shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold">14. General Provisions</h2>
              <h3 className="text-xl font-medium">14.1 Entire Agreement</h3>
              <p>
                These Terms, together with our Privacy Policy, constitute the entire agreement between you and Scenra regarding the Service.
              </p>
              <h3 className="text-xl font-medium">14.2 Severability</h3>
              <p>
                If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect.
              </p>
              <h3 className="text-xl font-medium">14.3 Waiver</h3>
              <p>
                Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights.
              </p>
              <h3 className="text-xl font-medium">14.4 Assignment</h3>
              <p>
                You may not assign or transfer these Terms without our prior written consent. We may assign our rights and obligations under these Terms without restriction.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold">15. Contact Us</h2>
              <p>
                If you have any questions about these Terms, please contact us at:
              </p>
              <ul>
                <li><strong>Email:</strong> legal@scenra.io</li>
                <li><strong>Website:</strong> https://scenra.io</li>
              </ul>
            </div>
          </section>
        </CardContent>
      </Card>

      {/* Version History */}
      <Card className="bg-muted/50">
        <CardContent className="p-6">
          <h3 className="font-semibold mb-2">Version History</h3>
          <ul className="text-sm text-muted-foreground space-y-1">
            <li><strong>v1.0</strong> (January 3, 2025) - Initial release</li>
          </ul>
        </CardContent>
      </Card>
    </div>
  )
}
